services:
  - type: web
    name: api-costamar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_costamar:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
